// Supabase Configuration
const SUPABASE_URL = 'https://iprwqfjsrkjfajxftzjk.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcndxZmpzcmtqZmFqeGZ0emprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMTE5MDIsImV4cCI6MjA3OTY4NzkwMn0.gLzny8Mih85581GadmmYFyOVeCJd8KSlhkUk1Qxr_Ng';
